### ISSUE TITLE
[QUESTION] What is the purpose of this plugin?

### ISSUE THREAD

**Issue by H4ppy-04** [beauwilliams/imnotaquitter.vim#3]
## About
I like the plugin, but I *do* have a couple of questions.

### Questions
Assuming that this plugin is not a gimmick:
 1. Why is it 'bad' to exit Vim?
 2. Why don't pros[^1] exit Vim?[^2]

[^1]: What constitutes a 'pro'?
[^2]: As stated in the [README](https://github.com/beauwilliams/imnotaquitter.vim?tab=readme-ov-file#imnotaquittervim) file

**Comment by ChilloManiac** [comment]
I guess it's because it's inefficient?

I'm assuming this plugin is to fix behavior such as

Make changes to project
Exit (N)vim
Run tests/lint in terminal
Enter (N)vim
Make more changes.

Using this plugin you would be forced to instead
 - Run tests/lint from inside your editor using a task-runner, terminal inside vim or other way
 - Open another terminal/tab/tmux and run inside there.

This preserves whatever state has been loaded (LSP, Plugins etc) and where you are located in your project. No reason to throw it away anytime you want to run a command in your terminal

**Comment by H4ppy-04** [comment]
> I guess it's because it's inefficient?

That makes sense. Reloading an LSP that has spent time indexing a large code-base would indeed be very inefficient (and slow). 


> Using this plugin you would be forced to instead
>
>    Run tests/lint from inside your editor using a task-runner, terminal inside vim or other way
>    Open another terminal/tab/tmux and run inside there.

Indeed a tmux-driven workflow for tests (or test runner plugin) would be much faster than exiting vim. 

> This preserves whatever state has been loaded (LSP, Plugins etc) and where you are located in your project. No reason to throw it away anytime you want to run a command in your terminal

I do like this idea, however I don't feel that a plugin is needed for this. (N)Vim has existing support for suspending a process (with `C-z`). IMHO a more graceful approach could be to map exit commands to suspend vim, instead of prompting the user with a message. 

The drawback of this 'alternative approach' would be incompatibility with operating systems such as Windows that only support sending process calls directly into the CPU from the kernel-level and don't natively support process suspension through the terminal[^1]. 

Thank you for your reply, and I'd love to hear your thoughts on this alternative approach!

[^1]: GNU/Bash does this nicely with a neat set of commands. Namely, [fg](https://www.ibm.com/docs/fi/aix/7.2?topic=f-fg-command), [bg](https://www.ibm.com/docs/fi/aix/7.2?topic=b-bg-command), disown, kill, jobs, etc
